<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<UserSecretsId>ICEBG.Data.Server-9042ECD1-A92B-4B48-B0EA-E54F5A5A6F9A</UserSecretsId>

		<!--<ContainerBaseImage>mcr.microsoft.com/dotnet/aspnet:8.0-rc1</ContainerBaseImage>-->
	</PropertyGroup>

	<ItemGroup>
		<ContainerPort Include="8080" Type="tcp" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
		<PackageReference Include="Grpc.AspNetCore.Server.Reflection" Version="2.71.0" />
		<PackageReference Include="Grpc.AspNetCore.Web" Version="2.71.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.5" />
		<PackageReference Include="Microsoft.AspNetCore.Components" Version="9.0.5" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.0.5" />
		<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.5" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.2" />
		<PackageReference Include="NLog.Extensions.AzureBlobStorage" Version="4.4.1" />
		<PackageReference Include="NLog.Web.AspNetCore" Version="5.4.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\ApplicationConfigurationServer\ApplicationConfigurationServer.csproj" />
	  <ProjectReference Include="..\ApplicationConfiguration\ApplicationConfiguration.csproj" />
	  <ProjectReference Include="..\DataTier\DataTier.csproj" />
	  <ProjectReference Include="..\ICEBG.Client.Burn\ICEBG.Client.Burn.csproj" />
	  <ProjectReference Include="..\Materia.Blazor\Materia.Blazor.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)'=='DevWebAssembly'">
		<ProjectReference Include="..\ICEBG.Blazor\ICEBG.Blazor.csproj" />
	</ItemGroup>

	<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
		<Copy SourceFiles="$(ProjectDir)appsettings.$(ConfigurationName).json" DestinationFiles="$(ProjectDir)appsettings.json" />
		<Copy SourceFiles="$(ProjectDir)nlog.$(ConfigurationName).config" DestinationFiles="$(ProjectDir)nlog.config" />
	</Target>

	<!--Compression directives (Note that the patterns are relative to wwwroot)-->
	<PropertyGroup>
		<CompressionIncludePatterns>$(CompressionIncludePatterns);**/*.css;**/*.js</CompressionIncludePatterns>
		<BuildCompressionFormats>gzip;brotli</BuildCompressionFormats>
		<PublishCompressionFormats>gzip;brotli</PublishCompressionFormats>
	</PropertyGroup>

</Project>
