name: GithubActionsRelease

############################################################################################################
# All of thes jobs runs commands only on a tag push in the MarkStega\ICEBG repository
# An 'ExitWorkflow' action is sorely needed
############################################################################################################
# NUGET_API_KEY is valid through 9/11/2021
############################################################################################################

on:
  push:
    tags:
      - '*' # Push events to matching *, i.e. 1.0, 20.15.10

env:
  appNameDS: 'icebg.web.ds'
  appNameUI: 'icebg.web.ui'
 
jobs:

############################################################################################################
# These jobs are used to gate actions. By creating these jobs we don't need to proliferate the repo checks
############################################################################################################
  perform-deployment:
    name: Perform deployment
    runs-on: ubuntu-latest
    if: github.repository == 'MarkStega/ICEBG' && github.actor != 'dependabot[bot]'
    steps:
    - name: Nothing to see here
      run: echo ""

  skip-deployment:
    name: Skip deployment
    runs-on: ubuntu-latest
    if: github.repository != 'MarkStega/ICEBG'
    steps:
    - name: Nothing to see here
      run: echo ""

  build-allowed:
    name: Build allowed
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
    - name: Nothing to see here
      run: echo ""

############################################################################################################
# Set unified suffix for the two deployed applications
############################################################################################################
  set-suffix:
    name: Create the date based suffix
    needs: [perform-deployment]
    runs-on: ubuntu-latest
    outputs:
      outputSuffix: ${{ steps.setSuffix.outputs.GlobalSuffix }}

    steps:
    - id: setSuffix
      run: echo "GlobalSuffix=$(date +'%Y-%m-%d--%H-%M-%S')--${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      shell: bash

############################################################################################################
# Build and deploy blazor DS image
############################################################################################################
  build-deploy-ds:
    name: Build and deploy ICEBG DS
    needs: [set-suffix]
    runs-on: ubuntu-latest

    steps:
    - name: Retrieve the global suffix
      run: echo "suffix=${{needs.set-suffix.outputs.outputSuffix}}" >> $GITHUB_ENV
      shell: bash

    - name: Checkout repository under $GITHUB_WORKSPACE so the job can access it 🛎️
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2

    - name: 'Docker login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Publish, tag, and push DS image
      run: |
        dotnet publish ICEBG.Web.DataServices/ICEBG.Web.DataServices.csproj --os linux --arch x64 --configuration Azure -p:PublishProfile=DefaultContainer -p:Version=${{ env.suffix }} -p:ContainerImageName=${{env.appNameDS}}
        docker tag ${{env.appNameDS}}:${{ env.suffix }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{env.appNameDS}}:${{ env.suffix }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{env.appNameDS}}:${{ env.suffix }}

############################################################################################################
# Build and deploy blazor UI image
############################################################################################################
  build-deploy-ui:
    name: Build and deploy ICEBG UI
    needs: [set-suffix]
    runs-on: ubuntu-latest

    steps:
    - name: Retrieve the global suffix
      run: echo "suffix=${{needs.set-suffix.outputs.outputSuffix}}" >> $GITHUB_ENV
      shell: bash

    - name: Checkout repository under $GITHUB_WORKSPACE so the job can access it 🛎️
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2

    - name: 'Docker login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Publish, tag, and push UI image
      run: |
        dotnet publish ICEBG.Web.UserInterface/ICEBG.Web.UserInterface.csproj --os linux --arch x64 --configuration Azure -p:PublishProfile=DefaultContainer -p:Version=${{ env.suffix }} -p:ContainerImageName=${{env.appNameUI}} --sc
        docker tag ${{env.appNameUI}}:${{ env.suffix }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{env.appNameUI}}:${{ env.suffix }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{env.appNameUI}}:${{ env.suffix }}

############################################################################################################
# Build blazor DS image
############################################################################################################
  build-ds:
    name: Build ICEBG DS
    needs: [skip-deployment, build-allowed]
    runs-on: windows-latest

    steps:
    - name: Set suffix as env variable
      run: echo "suffix=$(date +'%Y-%m-%d--%H-%M-%S')--${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      shell: bash

    - name: Checkout repository under $GITHUB_WORKSPACE so the job can access it 🛎️
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2

    - name: Build DS image
      run: |
        dotnet build ICEBG.Web.DataServices/ICEBG.Web.DataServices.csproj --os linux --arch x64 --configuration Azure -p:Version=${{ env.suffix }}

############################################################################################################
# Build blazor UI image
############################################################################################################
  build-ui:
    name: Build ICEBG UI
    needs: [skip-deployment, build-allowed]
    runs-on: windows-latest

    steps:
    - name: Set suffix as env variable
      run: echo "suffix=$(date +'%Y-%m-%d--%H-%M-%S')--${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      shell: bash

    - name: Checkout repository under $GITHUB_WORKSPACE so the job can access it 🛎️
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2

    - name: Build UI image
      run: |
        dotnet build ICEBG.Web.UserInterface/ICEBG.Web.UserInterface.csproj --os linux --arch x64 --configuration Azure -p:Version=${{ env.suffix }}
